name: playtomic_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: 4.19.2
  google_fonts: ^6.2.1
  getwidget: ^4.0.0
  intl_phone_number_input: ^0.7.4
  cloud_firestore: ^4.17.2
  flutter_svg: ^2.0.10+1
  logger: ^2.3.0
  font_awesome_flutter: ^10.7.0
  latlong2: ^0.9.1
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Naville
      fonts:
        - asset: assets/fonts/Naville-Regular.ttf
    - family: Noto
      fonts:
        - asset: assets/fonts/NotoSans.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
