// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMpNqvL39SeID2Vm0ZiAMknPS1oI2ZX30',
    appId: '1:132132514878:web:f03b1a18d51709477e756f',
    messagingSenderId: '132132514878',
    projectId: 'playtomic-b82bd',
    authDomain: 'playtomic-b82bd.firebaseapp.com',
    storageBucket: 'playtomic-b82bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEgBHxbdP1vG34AVFcGdd6xUoHL_NZ1XI',
    appId: '1:132132514878:android:6e292f903773c4637e756f',
    messagingSenderId: '132132514878',
    projectId: 'playtomic-b82bd',
    storageBucket: 'playtomic-b82bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuypYILgw7a1DwdEnWwzYGWBf_G8pJLEc',
    appId: '1:132132514878:ios:448a6600f40bbfee7e756f',
    messagingSenderId: '132132514878',
    projectId: 'playtomic-b82bd',
    storageBucket: 'playtomic-b82bd.appspot.com',
    iosBundleId: 'com.example.playtomicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuypYILgw7a1DwdEnWwzYGWBf_G8pJLEc',
    appId: '1:132132514878:ios:448a6600f40bbfee7e756f',
    messagingSenderId: '132132514878',
    projectId: 'playtomic-b82bd',
    storageBucket: 'playtomic-b82bd.appspot.com',
    iosBundleId: 'com.example.playtomicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMpNqvL39SeID2Vm0ZiAMknPS1oI2ZX30',
    appId: '1:132132514878:web:99cb153d4e82c9e67e756f',
    messagingSenderId: '132132514878',
    projectId: 'playtomic-b82bd',
    authDomain: 'playtomic-b82bd.firebaseapp.com',
    storageBucket: 'playtomic-b82bd.appspot.com',
  );
}
